name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Manual sparse checkout to avoid submodule issues
      - name: Manual checkout
        run: |
          # Initialize git repo
          git init
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
          # Configure sparse checkout to exclude problematic path
          git sparse-checkout init
          git sparse-checkout set --no-cone '/*' '!linkedin-lead-analysis'
          
          # Fetch and checkout
          git fetch --depth=1 origin ${{ github.ref }}
          git checkout FETCH_HEAD
          
          # Create placeholder to prevent git from looking for submodules
          touch .gitmodules
          
          # Configure git identity
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages-app
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }} 