name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Manually prepare environment first
      - name: Prepare environment
        run: |
          mkdir -p $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          touch .gitmodules
          echo "[submodule \"linkedin-lead-analysis\"]" > .gitmodules
          echo "    path = linkedin-lead-analysis" >> .gitmodules
          echo "    url = https://example.com/non-existent-repo.git" >> .gitmodules
      
      # Use standard checkout action but with specific parameters
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          path: .
      
      # Clean up problem submodule
      - name: Remove problematic submodule
        run: |
          rm -rf linkedin-lead-analysis
          git config --local --remove-section submodule.linkedin-lead-analysis || true
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages-app
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }} 