name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Directly clone repository using Git commands instead of checkout action
      - name: Direct Git Clone
        run: |
          # Clone without submodules
          git clone --no-checkout --filter=blob:none --depth=1 "https://github.com/${GITHUB_REPOSITORY}.git" .
          # Skip clone of submodules (critical!)
          git -c protocol.version=2 -c submodule.recurse=false -c advice.detachedHead=false checkout "${GITHUB_SHA}"
          # Verify contents
          ls -la
          # Remove any problematic directories
          rm -rf linkedin-lead-analysis || true
          # Clean .gitmodules file 
          echo "# Submodules disabled" > .gitmodules
          # Verify the gh-pages-app directory exists
          ls -la gh-pages-app || echo "Warning: gh-pages-app directory not found"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages-app
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }} 