name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          
      - name: Fix submodule issues
        run: |
          echo "Cleaning any nested .git directories"
          find . -path "*/linkedin-lead-analysis/.git" -type d -exec rm -rf {} + || true
          # Create empty .gitmodules file to prevent errors
          touch .gitmodules
          # Remove any Git submodule references
          git config --local --unset-all submodule.linkedin-lead-analysis.url || true
          git config --local --unset-all submodule.linkedin-lead-analysis.active || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages-app
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }} 